build:
  image: node:4-onbuild
  commands:
    - npm install
    - npm test

deploy:
  rsync:
    user: lfmadmin
    host: lfmtest-hub-metrics
    port: 22
    source: copy/files/from
    target: send/files/to
    delete: false
    recursive: true
