build:
  image: node:4-onbuild
  commands:
    - npm install
    - npm test

publish:
  docker:
    username: simoncrabtree
    password: $$DOCKER_PASSWORD
    email: simon@crabsticks.net
    repo: simoncrabtree/hubble
    tag: latest
    file: Dockerfile
