build:
  image: node:4-onbuild
  commands:
    - npm install
    - npm test

deploy:
  rsync:
    user: lfmadmin
    host: 10.96.0.5
    port: 22
    source: .
    target: ~/deployments/hubble
    delete: false
    recursive: true
