apiVersion: v1
kind: ReplicationController
metadata:
  name: hubble-replication-controller
  labels:
    name: hubble
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: hubble
    spec:
      containers:
      - name: hubble-rc-pod
        image: simon/hubble
        ports:
        - containerPort: 8002